name: Storybook to GitHub Pages

on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
   build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and deploy Storybook
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./storybook-static

