name: Storybook to GitHub Pages

on:
  push:
    branches:
      - "main" # change to the branch you wish to deploy from

permissions:
  contents: write
  contents: write
  pages: write
  id-token: write

jobs:
   build-and-deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: sb-ghp
          folder: storybook-static
          lfs: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}